services:
  mysql:
    image: mysql:latest
    container_name: mysql_bkup
    security_opt:
      - seccomp:unconfined
    expose:
      - 3306
    volumes:
      - data:/var/lib/mysql
      - ${VOLUME_PATH}/backup:/backup
    environment:
      - MYSQL_DATABASE="TEST"
      - MYSQL_ROOT_PASSWORD="TEST"
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect" ]
      timeout: 5s
      retries: 10

  backup:
    build: .
    image: mysqlbkp
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ${VOLUME_PATH}/backup:/backup
    environment:
      - MYSQL_HOST=mysql_bkup
      - MYSQL_USER=root
      - MYSQL_PASS="TEST"
      - MAX_BACKUPS=1
      - INIT_BACKUP=1
      - CRON_TIME=0 0 * * *
    restart: unless-stopped

volumes:
  data:
